### ISSUE TITLE
AB Test: Purchase Request

### ISSUE THREAD

**Issue by briansw** [artsy/microgravity#44]
This test affects artworks that are for sale and have an exact price listed. We'll test the feature with a select group of partners at first (list of partners still in progress).

Related Force issue: https://github.com/artsy/force/issues/261
#### Todos
- [ ] Change the name of ecommerce artwork "Buy" buttons to "Purchase"
- [ ] Artwork page template updates
- [ ] Responsive checkout page (see force issue)
- [ ] Responsive payoff page (see force issue)
- [ ] Formatting of message field
#### Artwork page template

![artwork-mg](https://cloud.githubusercontent.com/assets/1022172/19248886/915ed8d8-8f00-11e6-8100-3fdd6a4aea57.jpg)
#### Formatting of message field

![email](https://cloud.githubusercontent.com/assets/1022172/19248758/d02f3414-8eff-11e6-9c63-cf89f02cd8c0.jpg)

**Comment by alloy** [comment]
I’m going to close this ticket for now, let’s re-open when we decide that we actually want to add this feature to MG at all.

/cc @tayapage6
